//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestClient
        ///
        ///1) Account Test
        ///2) Readings Test
        ///3) Exit
        ///.
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountId,MeterReadingDateTime,MeterReadValue
        ///2344,22/04/2019 09:24,01002
        ///2233,22/04/2019 12:25,00323
        ///8766,22/04/2019 12:25,03440
        ///2344,22/04/2019 12:25,01002
        ///2345,22/04/2019 12:25,45522
        ///2346,22/04/2019 12:25,999999
        ///2347,22/04/2019 12:25,00054
        ///2348,22/04/2019 12:25,00123
        ///2349,22/04/2019 12:25,VOID
        ///2350,22/04/2019 12:25,05684
        ///2351,22/04/2019 12:25,57579
        ///2352,22/04/2019 12:25,00455
        ///2353,22/04/2019 12:25,01212
        ///2354,22/04/2019 12:25,00889
        ///2355,06/05/2019 09:24,00001
        ///2356,07/05/2019 09:24,00000
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Meter_Reading_2 {
            get {
                return ResourceManager.GetString("Meter_Reading 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountId,FirstName,LastName
        ///2344,Tommy,Test
        ///2233,Barry,Test
        ///8766,Sally,Test
        ///2345,Jerry,Test
        ///2346,Ollie,Test
        ///2347,Tara,Test
        ///2348,Tammy,Test
        ///2349,Simon,Test
        ///2350,Colin,Test
        ///2351,Gladys,Test
        ///2352,Greg,Test
        ///2353,Tony,Test
        ///2355,Arthur,Test
        ///2356,Craig,Test
        ///6776,Laura,Test
        ///4534,JOSH,TEST
        ///1234,Freya,Test
        ///1239,Noddy,Test
        ///1240,Archie,Test
        ///1241,Lara,Test
        ///1242,Tim,Test
        ///1243,Graham,Test
        ///1244,Tony,Test
        ///1245,Neville,Test
        ///1246,Jo,Test
        ///1247,Jim,Test
        ///1248,Pam,Test
        ///.
        /// </summary>
        internal static string Test_Accounts_2 {
            get {
                return ResourceManager.GetString("Test_Accounts 2", resourceCulture);
            }
        }
    }
}
